### ISSUE TITLE
It fail to install after upgrading to El Capitan

### ISSUE THREAD

**Issue by jfromaniello** [Southern/node-x509#26]
This is the output:

```
> x509@0.0.4 preinstall /myproject/something/foo/node_modules/.staging/x509-af6e96e0e7b4c49d655e9d9be3833418
> make

cat version.gypi | sed -e s/{{VERSION}}/0.0.4/ > build/version.gypi
node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@0.10.40 | darwin | x64
gyp info spawn python2
gyp info spawn args [ '/Users/jose/.nave/installed/0.10.40/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/myproject/something/foo/node_modules/.staging/x509-af6e96e0e7b4c49d655e9d9be3833418/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jose/.nave/installed/0.10.40/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jose/.node-gyp/0.10.40/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jose/.node-gyp/0.10.40',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jose/.nave/installed/0.10.40/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/myproject/something/foo/node_modules/.staging/x509-af6e96e0e7b4c49d655e9d9be3833418',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/x509/src/addon.o
In file included from ../src/addon.cc:2:
../include/x509.h:10:10: fatal error: 'openssl/asn1.h' file not found
#include <openssl/asn1.h>
         ^
1 error generated.
make[1]: *** [Release/obj.target/x509/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jose/.nave/installed/0.10.40/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Users/jose/.nave/installed/0.10.40/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /myproject/something/foo/node_modules/.staging/x509-af6e96e0e7b4c49d655e9d9be3833418
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
make: *** [all] Error 1
npm info lifecycle x509@0.0.4~preinstall: Failed to exec preinstall script
```

**Comment by jfromaniello** [comment]
Ignore this thread, latest version installs ok.
