### ISSUE TITLE
SegFault on certain certificates

### ISSUE THREAD

**Issue by mwpnl** [Southern/node-x509#37]
When parsing certain certificates, for some reason a segmentation fault occurs that comes from the x509 module. When parsing the certificate directly from the CLI with openSSL no error occurs.

An example of the certificate is the one added as cert.txt: (rename to cert.pem)
[cert.txt](https://github.com/Southern/node-x509/files/411725/cert.txt)

When executing on:
* centOS 7.2.1511 64bit
* Node version 6.3.1
* X509 version 0.2.6

the following stack trace occurs:

`PID 10938 received SIGSEGV for address: 0x0
/root/test/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x1a7b)[0x7f6556050a7b]
/lib64/libpthread.so.0(+0xf100)[0x7f655882f100]
/lib64/libc.so.6(+0x13aa4f)[0x7f6558598a4f]
node(BUF_strlcpy+0x50)[0x8181c0]
/root/test/node_modules/x509/build/Release/x509.node(_Z9try_parseRKSs+0x965)[0x7f6556257115]
/root/test/node_modules/x509/build/Release/x509.node(_Z10parse_certRKN3Nan20FunctionCallbackInfoIN2v85ValueEEE+0x58)[0x7f6556257b88]
/root/test/node_modules/x509/build/Release/x509.node(+0x2b96)[0x7f6556255b96]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0xfe)[0x9484ae]
node[0x993bfd]
node[0x99414a]
[0x288f8890961b]
`

The simple node.js application used to execute the X509 is the following (I've added the node-segfault-handler  module to make sure I get the above stack trace):

[test.txt](https://github.com/Southern/node-x509/files/411733/test.txt) (rename to test.js).

If I execute `openssl x509 -in cert.pem` from the CLI I get the expected parsed result of the certificate.

The error occurs with only a few certificates, almost all other certificates are parsed with ease, so any idea on what could be wrong or how to fix this would be much appreciated.

**Comment by Rush** [comment]
Sorry to say but even demangled, this stacktrace seems quite useless:
```
PID 10938 received SIGSEGV for address: 0x0 /root/test/node_modules/segfault-handler/build/Release/segfault-handler.node( 0x1a7b)[0x7f6556050a7b] /lib64/libpthread.so.0( 0xf100)[0x7f655882f100]

 /lib64/libc.so.6( 0x13aa4f)[0x7f6558598a4f] node(BUF_strlcpy 0x50)[0x8181c0] /root/test/node_modules/x509/build/Release/x509.node(try_parse(std::string const&) 0x965)[0x7f6556257115] 

/root/test/node_modules/x509/build/Release/x509.node(parse_cert(Nan::FunctionCallbackInfo<v8::Value> const&) 0x58)[0x7f6556257b88] /root/test/node_modules/x509/build/Release/x509.node( 0x2b96)[0x7f6556255b96]

node(v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) 0xfe)[0x9484ae] node[0x993bfd] node[0x99414a] [0x288f8890961b] 
```



It would be helpful if you could compile node-x509 in debug mode. `git clone` it from github to somewhere and inside do `npm install && node-gyp rebuild --debug`. If you're missing the node-gyp tool then you can install it with `npm install -g node-gyp` (if you use NVM you can do it as a normal user).

In your application directory do `rm -rf node_modules/x509 && ln -rs /path/to/x509/repo node_modules/x509`.

Now you can produce some useful outputs:
```
$ valgrind node test-program.js cert.crt
```

and
```
$ gdb --args node test-program.js cert.crt
> run
# after it crashes, write the below
> bt
```

Paste the resulting stacktraces here and I'm sure @Southern will be able to assist.

**Comment by mwpnl** [comment]
Thanks! That's very fast and a helpful guide on how to (re)build a module in debug mode.

**Comment by mwpnl** [comment]
I'm not quite sure if adding the complete stack in-line was what you had in mind, but if it's easier to put the stack in a separate file I figured I can always edit this comment and do it afterwards.

Does this provide enough information be be useful? I'd love to be able to help out more, but my knowledge on this subject is too limited.

These are the results from running valgrind:
<pre>
==11704== Memcheck, a memory error detector
==11704== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==11704== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==11704== Command: node test.js
==11704== Parent PID: 11097
==11704== 
==11704== Warning: set address range perms: large range [0x202781af1000, 0x2027a1af1000) (noaccess)
==11704== Conditional jump or move depends on uninitialised value(s)
==11704==    at 0x4C2CBA9: strlen (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==11704==    by 0x8181BF: BUF_strlcpy (in /usr/bin/node)
==11704==    by 0x98463F4: parse_date(asn1_string_st*) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x98469F9: try_parse(std::string const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9847B87: parse_cert(Nan::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9845B95: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9484AD: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /usr/bin/node)
==11704==    by 0x993BFC: ??? (in /usr/bin/node)
==11704==    by 0x994149: ??? (in /usr/bin/node)
==11704==    by 0x202781E0961A: ???
==11704==    by 0x202781F4D2BE: ???
==11704==    by 0x202781F3E160: ???
==11704== 
==11704== Conditional jump or move depends on uninitialised value(s)
==11704==    at 0x4C2CBB8: strlen (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==11704==    by 0x8181BF: BUF_strlcpy (in /usr/bin/node)
==11704==    by 0x98463F4: parse_date(asn1_string_st*) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x98469F9: try_parse(std::string const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9847B87: parse_cert(Nan::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9845B95: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9484AD: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /usr/bin/node)
==11704==    by 0x993BFC: ??? (in /usr/bin/node)
==11704==    by 0x994149: ??? (in /usr/bin/node)
==11704==    by 0x202781E0961A: ???
==11704==    by 0x202781F4D2BE: ???
==11704==    by 0x202781F3E160: ???
==11704== 
==11704== Conditional jump or move depends on uninitialised value(s)
==11704==    at 0x4C2CBA9: strlen (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==11704==    by 0x8181BF: BUF_strlcpy (in /usr/bin/node)
==11704==    by 0x98463F4: parse_date(asn1_string_st*) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9846A55: try_parse(std::string const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9847B87: parse_cert(Nan::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9845B95: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9484AD: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /usr/bin/node)
==11704==    by 0x993BFC: ??? (in /usr/bin/node)
==11704==    by 0x994149: ??? (in /usr/bin/node)
==11704==    by 0x202781E0961A: ???
==11704==    by 0x202781F4D2BE: ???
==11704==    by 0x202781F3E160: ???
==11704== 
==11704== Conditional jump or move depends on uninitialised value(s)
==11704==    at 0x4C2CBB8: strlen (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==11704==    by 0x8181BF: BUF_strlcpy (in /usr/bin/node)
==11704==    by 0x98463F4: parse_date(asn1_string_st*) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9846A55: try_parse(std::string const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9847B87: parse_cert(Nan::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9845B95: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9484AD: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /usr/bin/node)
==11704==    by 0x993BFC: ??? (in /usr/bin/node)
==11704==    by 0x994149: ??? (in /usr/bin/node)
==11704==    by 0x202781E0961A: ???
==11704==    by 0x202781F4D2BE: ???
==11704==    by 0x202781F3E160: ???
==11704== 
==11704== Conditional jump or move depends on uninitialised value(s)
==11704==    at 0x4C2CBA9: strlen (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==11704==    by 0x8181BF: BUF_strlcpy (in /usr/bin/node)
==11704==    by 0x9847114: try_parse(std::string const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9847B87: parse_cert(Nan::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9845B95: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9484AD: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /usr/bin/node)
==11704==    by 0x993BFC: ??? (in /usr/bin/node)
==11704==    by 0x994149: ??? (in /usr/bin/node)
==11704==    by 0x202781E0961A: ???
==11704==    by 0x202781F4D2BE: ???
==11704==    by 0x202781F3E160: ???
==11704==    by 0x202781F3DDAF: ???
==11704== 
==11704== Invalid read of size 1
==11704==    at 0x4C2CBA2: strlen (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==11704==    by 0x8181BF: BUF_strlcpy (in /usr/bin/node)
==11704==    by 0x9847114: try_parse(std::string const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9847B87: parse_cert(Nan::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9845B95: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (in /root/node-x509/build/Release/x509.node)
==11704==    by 0x9484AD: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /usr/bin/node)
==11704==    by 0x993BFC: ??? (in /usr/bin/node)
==11704==    by 0x994149: ??? (in /usr/bin/node)
==11704==    by 0x202781E0961A: ???
==11704==    by 0x202781F4D2BE: ???
==11704==    by 0x202781F3E160: ???
==11704==    by 0x202781F3DDAF: ???
==11704==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==11704== 
==11704== 
==11704== HEAP SUMMARY:
==11704==     in use at exit: 439,217 bytes in 575 blocks
==11704==   total heap usage: 15,852 allocs, 15,277 frees, 44,073,888 bytes allocated
==11704== 
==11704== LEAK SUMMARY:
==11704==    definitely lost: 645 bytes in 4 blocks
==11704==    indirectly lost: 52 bytes in 2 blocks
==11704==      possibly lost: 22,668 bytes in 131 blocks
==11704==    still reachable: 415,852 bytes in 438 blocks
==11704==         suppressed: 0 bytes in 0 blocks
==11704== Rerun with --leak-check=full to see details of leaked memory
==11704== 
==11704== For counts of detected and suppressed errors, rerun with: -v
==11704== Use --track-origins=yes to see where uninitialised values come from
==11704== ERROR SUMMARY: 12 errors from 6 contexts (suppressed: 1 from 1)
</pre>

And when running gdb, the following trace occurs (not sure if anything after number 7 is relevant):

<pre>
(gdb) run
Starting program: /usr/bin/node test.js
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff7ff8700 (LWP 11631)]
[New Thread 0x7ffff6bd0700 (LWP 11632)]
[New Thread 0x7ffff63cf700 (LWP 11633)]
[New Thread 0x7ffff5bce700 (LWP 11634)]
[New Thread 0x7ffff53cd700 (LWP 11635)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6d0ba4f in __strlen_sse42 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6d0ba4f in __strlen_sse42 () from /lib64/libc.so.6
#1  0x00000000008181c0 in BUF_strlcpy ()
#2  0x00007ffff49ca115 in try_parse(std::string const&) () from /root/node-x509/build/Release/x509.node
#3  0x00007ffff49cab88 in parse_cert(Nan::FunctionCallbackInfo<v8::Value> const&) () from /root/node-x509/build/Release/x509.node
#4  0x00007ffff49c8b96 in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) () from /root/node-x509/build/Release/x509.node
#5  0x00000000009484ae in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#6  0x0000000000993bfd in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) ()
#7  0x000000000099414a in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
#8  0x00001d5a8820961b in ?? ()
#9  0x00001d5a88209561 in ?? ()
#10 0x00007fffffffda90 in ?? ()
#11 0x00007fffffffdb08 in ?? ()
#12 0x00001d5a8834d2bf in ?? ()
#13 0x00002fa45c661131 in ?? ()
#14 0x00002fa45c65b239 in ?? ()
#15 0x00002de61e0dba89 in ?? ()
#16 0x00002fa45c661131 in ?? ()
#17 0x000024fccc004189 in ?? ()
#18 0x000024fccc004189 in ?? ()
#19 0x000024fccc004189 in ?? ()
#20 0x000024fccc004189 in ?? ()
#21 0x000024fccc004189 in ?? ()
#22 0x00002fa45c6611c9 in ?? ()
#23 0x00002de61e0dab11 in ?? ()
#24 0x00007fffffffdb58 in ?? ()
#25 0x00001d5a8833e161 in ?? ()
#26 0x00002fa45c65b239 in ?? ()
#27 0x00002de61e0d8bf9 in ?? ()
#28 0x00002fa45c6611c9 in ?? ()
#29 0x000024fccc004189 in ?? ()
#30 0x00002de61e0f6769 in ?? ()
#31 0x00002de61e0d8bf9 in ?? ()
#32 0x00002de61e0d6489 in ?? ()
#33 0x000024fccc0ac501 in ?? ()
#34 0x00007fffffffdc08 in ?? ()
#35 0x00001d5a8833ddb0 in ?? ()
#36 0x00002de61e0d64e9 in ?? ()
#37 0x00002de61e0d4749 in ?? ()
#38 0x00002de61e0d47d1 in ?? ()
#39 0x00002de61e0d65c1 in ?? ()
#40 0x00002de61e0d48c9 in ?? ()
#41 0x00002de61e0d48c9 in ?? ()
#42 0x000024fccc0ba011 in ?? ()
#43 0x000024fccc004189 in ?? ()
#44 0x0000000000000000 in ?? ()
</pre>

**Comment by Rush** [comment]
Almost good but there are still no line numbers as I see that a Release version is being loaded `/root/node-x509/build/Release/x509.node`. We need there to be `Debug`. I suspect that `node-gyp rebuild --debug` did not work for some reason. Also you can try removing the Release version by hand.

**Comment by mwpnl** [comment]
It took me a while to find out what you ment with the line numbers, but I _think_ I've got it right this time!

I updated my comment above with the fresh stack traces with line numbers to keep the discussion clean, hope that's okay.

**Comment by Southern** [comment]
I'm pretty busy for the next couple of days. It'll probably be the weekend before I can get around to it.

@yorkie Do you have any free time to check this out?

**Comment by yorkie** [comment]
@mwpnl @Southern after taking a look at gdb results, I think the potential missing line is [here](https://github.com/Southern/node-x509/blob/master/src/x509.cc#L281):

```cc
char *data = (char*) malloc(bptr->length + 1);
BUF_strlcpy(data, bptr->data, bptr->length + 1);
```

We didn't check if the `data` has been able to access after calling `malloc`, therefore, @mwpnl may I ask you to update the "src/x509.cc" at line 281 like the following diff:

```diff
diff --git a/src/x509.cc b/src/x509.cc
index acad881..016f45d 100644
--- a/src/x509.cc
+++ b/src/x509.cc
@@ -279,6 +279,12 @@ Local<Value> try_parse(const std::string& dataString) {
     BIO_set_close(ext_bio, BIO_CLOSE);

     char *data = (char*) malloc(bptr->length + 1);
+    if (data == NULL) {
+      BIO_free(ext_bio);
+      printf("malloc in try_parse result is not accessible\n");
+      break;
+    }
+
     BUF_strlcpy(data, bptr->data, bptr->length + 1);
     data = trim(data, bptr->length);
```

And try to run with gdb again, and see what happened in details, thanks :-)

**Comment by mwpnl** [comment]
@yorkie was completely right, the issue was with a bptr->data that was completely empty. I've adapted the above code diff and made pull request #39, that solves this issue in the certs I mentioned above.

Looking forward to see your comments on this!

**Comment by yorkie** [comment]
Okay @mwpnl will comment when I get home later, thanks :)

**Comment by jthomerson** [comment]
@Southern what's the status of this issue? I see on the PR #39 that you said

> With the lack of activity in this PR, I'm starting to believe this was a case of a certificate being malformed or some other factor than this specific module and was solved by correcting that issue.

Maybe it is from a malformed certificate, but still we need the x509 module to avoid a segfault when reading such a certificate. I'm trying to read through all certificate transparency logs and I'm getting a segfault when reading a different certificate. Ironically (or not), the cert is by the same issuer and for the same subject as the one @mwpnl originally reported with this issue, although it's a different cert.

I've pasted the cert below. You can also see details about it at https://crt.sh/?id=6039630. I've actually tried every cert that's in the CT logs that has that subject common name (https://crt.sh/?q=Cybertrust+Japan+EV+CA+G2+OCSP+Responder), and every one of them fails exactly the same.

```
-----BEGIN CERTIFICATE-----
MIIDzjCCAragAwIBAgIUN5EK0B6cCK/IL6jSmZ6ifu6olsMwDQYJKoZIhvcNAQEF
BQAwVjELMAkGA1UEBhMCSlAxIzAhBgNVBAoTGkN5YmVydHJ1c3QgSmFwYW4gQ28u
LCBMdGQuMSIwIAYDVQQDExlDeWJlcnRydXN0IEphcGFuIEVWIENBIEcyMB4XDTE0
MTEyODA4MzgyNFoXDTE2MTEzMDE0NTk1OVowZTELMAkGA1UEBhMCSlAxIzAhBgNV
BAoTGkN5YmVydHJ1c3QgSmFwYW4gQ28uLCBMdGQuMTEwLwYDVQQDEyhDeWJlcnRy
dXN0IEphcGFuIEVWIENBIEcyIE9DU1AgUmVzcG9uZGVyMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA2P4xPrFd60ZbUfGe3YQG9DGgkSC1DKFIOosVct0x
5uasy+EIfdXy2L1Jicd4RlLMdkCfm/6f4DOKOQu174mxLHL+NcHlGU8+iFtBkmvp
sA8sonqGgfkaEbyJLuQbWAkbCG/uZfpdQz87aAN2ouqRvxweW+bJON50P3N95LsA
C9dZR2+GTeP/WY5hC/4DkUYlv+bl96xW6cHr31ViF/2QwGjwQuLIa9IN4+Ll5BV3
8pOFVbKpy9qecISAdXj4COoOpumz871sItHK7olNJQvpClu558SUsyZk3ydDI8gH
yjzu8I97UmxcMYs3/ughyWx1zz385lXNLLPTlxV3JXFe+QIDAQABo4GEMIGBMAkG
A1UdEwQCMAAwDwYJKwYBBQUHMAEFBAIFADAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0l
BAwwCgYIKwYBBQUHAwkwHwYDVR0jBBgwFoAUkUMF7LRqFU/c4e6GVlwR0CorjV8w
HQYDVR0OBBYEFMXTVhjIBJtS0b9ry+4DcEutk/inMA0GCSqGSIb3DQEBBQUAA4IB
AQBa+iAO9iie7cNno4RF2Tx+gt85SZKxsRA9ZOiU8dbAx8+gCE3Jfjp3UKZoW04Z
698WAh3CDkofJmg5E2g/hgt+YQ/2rZU70pFYO8T0NOemOOUbSgzw2rKt3Vk3SjsU
ciyo8osNG1ZaQEn1wXkur3pYuaKFeh28bSS6QjiI7I+KK02VGOtI+DclGzk0OU5O
ePl2rLTC0Y7o+JVMk6bjyhGhY1O2JWriYzeLLvPSZh0T13/Yes55S8eda0maFPYg
xspv/+0a1AMB+3aBM0HZQmKZf9mAHKDCDZtqrOfBKVUJ2MIeKnxPW9730HFAlMiR
XakqqIPar5fIWlZum0Jb0lQy
-----END CERTIFICATE-----
```

Test script:

```js
var x509 = require('x509'),
    cert = require('fs').readFileSync(process.argv[2]).toString();

console.log(cert);
console.log(x509.parseCert(cert));
```

Run it with `node test.js ~/Downloads/6039630.crt ` after downloading one of the certs from crt.sh for example.

Thanks!

**Comment by jthomerson** [comment]
It should be noted that every one of those certs parses fine with openssl on the CLI, so optimally x509 would parse them as well, returning the same info that openssl does.

**Comment by mwpnl** [comment]
@jthomerson Looping through the CT log is exactly how I came about this issue. Great find that they're all certificates with the came CN!

After my initial PR #39 another user made a similar request in PR #56.

The - to me - cryptic review comments by @yorkie on my PR made me abandon the PR. With the best intentions of the word, I fail to see what's wrong. And, the solution works for me, travelling through the CT log.

If anyone would be willing to elaborate some more on the proposed fixes, I'd me more than happy to make those changes anew.
