### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 67.

### ISSUE THREAD

**Issue by DigitalLeaves** [Southern/node-x509#80]
Getting lots of these lately, I'm unable to run code using the x509 module. Using node v11.10.0.
```
15|ereside | Error: Module version mismatch. Expected 48, got 67.
15|ereside |     at Error (native)
15|ereside |     at Object.Module._extensions..node (module.js:604:18)
15|ereside |     at Module.load (module.js:494:32)
15|ereside |     at tryModuleLoad (module.js:453:12)
15|ereside |     at Function.Module._load (module.js:445:3)
15|ereside |     at Module.require (module.js:504:17)
15|ereside |     at require (internal/module.js:20:19)
15|ereside |     at Object.<anonymous> (/route/to/project/node_modules/x509/index.js:1:74)
```

Any help greatly appreciated.
Already tried npm rebuild, removing node_modules and installing everything again, etc...
Npm version: 6.8.0
Server is Linux Debian 8.11.

**Comment by DigitalLeaves** [comment]
This is due to a node mismatch. Can be solved removing node and npm and reinstalling them from scratch. I suspect is due to some libraries being stored somewhere in /usr/local/lib/node_modules that just won't update.
